
- name: Hello World Sample
  hosts: app1_test_web
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
    - name: Install rsync
      ansible.builtin.yum:
        name: rsync
        state: latest
